name: testProject               #worklfow name
on: push                        #event
jobs:                           #job fields
  test:                         #my first job name 
    runs-on: ubuntu-latest      #running environment
    steps:                      #can start off multiple steps from here
      - name: Get Code          #can checkout repositry on to the running env so that our workflow can access it
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18 
      - run: npm ci
      - run: npm test

